### ISSUE TITLE
Git/Debugging tutorial not found

### ISSUE THREAD

**Issue by julianengel** [DCHacksLive/dchackslive.github.io#1]
http://live.dchacks.org/tracks/git.html
http://live.dchacks.org/tracks/debug.html

Hey guys. I was looking trough your website and i was testing everything out. When you go through tutorials and press github or debugging, they don't get found. Just wanted to let you know! The event is great

**Comment by stormsurfer98** [comment]
Thanks for letting us know. We will fix this ASAP.

Thanks,
Shrey
